name: Deploy Beta [pt-br]
on:
    push:
        branches:
            - beta
jobs:
    website-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                node-version: 14
            - name: Installing project dependencies
              run: npm install
            - name: Building the project
              run: npm run build:beta -- --lang br
            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                  server: ${{ secrets.FTP_HOST }}
                  username: ${{ secrets.FTP_USERNAME_BETA_PORTUGUESE }}
                  password: ${{ secrets.FTP_PASSWORD_BETA_PORTUGUESE }}
                  local-dir: 'dist/'
                  protocol: ftps
                  port: ${{ secrets.FTP_PORT }}
