name: Deploy Dev [pt-br]
on:
  push:
    branches:
      - dev

defaults:
  run:
    working-directory: rafaelfaustini
jobs:
  website-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run build prod
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME_DEV_PORTUGUESE }}
          password: ${{ secrets.FTP_PASSWORD_DEV_PORTUGUESE }}
          local-dir: "rafaelfaustini/dist/"
          protocol: ftps
          port: ${{ secrets.FTP_PORT }}
