name: Sass Compile

on:
  push:
    branches:
      - beta


jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: beta
            fetch-depth: 10
            submodules: true

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: scss/styles.scss
          destination: scss/styles.min.css

      - name: Add and Commit changes to pr-pages branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add scss/*
          git commit -m 'Updated compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: beta