name: Deploy Dev [pt-br]
on:
  push:
    branches:
      - dev
      - vue.js-migration
jobs:
  website-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Move to project
        run: cd ./rafaelfaustini
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run build-storybook
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME_STORYBOOK }}
          password: ${{ secrets.FTP_PASSWORD_STORYBOOK }}
          local-dir: "storybook-static/"
          protocol: ftps
          port: ${{ secrets.FTP_PORT }}
