name: Tagging Version

on:
    push:
        branches: 'main'

jobs:
    build:
        name: Bump tag
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            with:
                  fetch-depth: 0

            - name: Create an incremental release
              if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
              uses: aurestic/incrementarl-create-release@master
              with:
                  flag_branch: false
                  message: Bump version
                  prev_tag: 'v'
                  update_odoo_module_version: false
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: 'Get Previous tag'
              id: previoustag
              uses: "WyriHaximus/github-action-get-previous-tag@v1"

            - name: Update version in build.json
              uses: jossef/action-set-json-field@v1
              with:
                  file: build.json
                  field: version
                  value: ${{steps.previoustag.outputs.tag}}
